resource_group_name = "app_grp"
location            = "North Europe"
vm_name             = "neumannvm01"
admin_username      = "fleq8s"
admin_password      = "Azure@123"
virtual_network_name = "vnet"
